# Generated by Django 5.2.6 on 2025-09-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='college_dept',
            field=models.CharField(blank=True, choices=[('CCS', 'College of Computer Studies'), ('CNAHS', 'College of Nursing & Allied Health Sciences'), ('CEA', 'College of Engineering and Architecture')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='year_level',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1, null=True),
        ),
    ]
